打开梯度检查点，仅训练unet，优化器改成带paged，offload vae，实在不行fp8训练


model_train_type = "sdxl-lora"
pretrained_model_name_or_path = "D:/AI_draw/sd-webui-aki-v4.8/models/Stable-diffusion/noobaiXLNAIXL_epsilonPred10Version.safetensors"
resume = ""
train_data_dir = "./train"
prior_loss_weight = 1
resolution = "1024,1024"
enable_bucket = true
min_bucket_reso = 640
max_bucket_reso = 1536
bucket_reso_steps = 32
output_name = "shibuki_kamone_Noob10"
output_dir = "./output"
save_model_as = "safetensors"
save_precision = "bf16"
save_every_n_epochs = 2
max_train_epochs = 16
train_batch_size = 1
gradient_checkpointing = true
network_train_unet_only = true
network_train_text_encoder_only = false
learning_rate = 0.0001
unet_lr = 0.0002
text_encoder_lr = 0.0001
lr_scheduler = "cosine_with_restarts"
lr_warmup_steps = 0
lr_scheduler_num_cycles = 1
optimizer_type = "PagedAdamW8bit"
network_module = "networks.lora"
network_dim = 16
network_alpha = 8
sample_prompts = "1girl, solo, --n lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts,signature, watermark, username, blurry,  --w 1024  --h 1024  --l 6  --s 28  --d 13377"
sample_sampler = "euler_a"
sample_every_n_epochs = 1
log_with = "tensorboard"
logging_dir = "./logs"
caption_extension = ".txt"
shuffle_caption = true
keep_tokens = 0
max_token_length = 255
seed = 1337
mixed_precision = "bf16"
full_fp16 = false
full_bf16 = true
xformers = true
lowram = false
cache_latents = true
cache_latents_to_disk = true
cache_text_encoder_outputs = false
persistent_data_loader_workers = true
multi_gpu = false
